In [1]:
import pandas as pd

In [2]:
data =  pd.read_csv("GO.csv")
data

symbol                       date    close      high        low     open  \
0      GOOG  2016-06-14 00:00:00+00:00   718.27   722.470   713.1200   716.48   
1      GOOG  2016-06-15 00:00:00+00:00   718.92   722.980   717.3100   719.00   
2      GOOG  2016-06-16 00:00:00+00:00   710.36   716.650   703.2600   714.91   
3      GOOG  2016-06-17 00:00:00+00:00   691.72   708.820   688.4515   708.65   
4      GOOG  2016-06-20 00:00:00+00:00   693.71   702.480   693.4100   698.77   
...     ...                        ...      ...       ...        ...      ...   
1253   GOOG  2021-06-07 00:00:00+00:00  2466.09  2468.000  2441.0725  2451.32   
1254   GOOG  2021-06-08 00:00:00+00:00  2482.85  2494.495  2468.2400  2479.90   
1255   GOOG  2021-06-09 00:00:00+00:00  2491.40  2505.000  2487.3300  2499.50   
1256   GOOG  2021-06-10 00:00:00+00:00  2521.60  2523.260  2494.0000  2494.01   
1257   GOOG  2021-06-11 00:00:00+00:00  2513.93  2526.990  2498.2900  2524.92   

       volume  adjClose   adjHigh     adjLow  adjOpen  adjVolume  divCash  \
0     1306065    718.27   722.470   713.1200   716.48    1306065      0.0   
1     1214517    718.92   722.980   717.3100   719.00    1214517      0.0   
2     1982471    710.36   716.650   703.2600   714.91    1982471      0.0   
3     3402357    691.72   708.820   688.4515   708.65    3402357      0.0   
4     2082538    693.71   702.480   693.4100   698.77    2082538      0.0   
...       ...       ...       ...        ...      ...        ...      ...   
1253  1192453   2466.09  2468.000  2441.0725  2451.32    1192453      0.0   
1254  1253253   2482.85  2494.495  2468.2400  2479.90    1253253      0.0   
1255  1006337   2491.40  2505.000  2487.3300  2499.50    1006337      0.0   
1256  1561733   2521.60  2523.260  2494.0000  2494.01    1561733      0.0   
1257  1262309   2513.93  2526.990  2498.2900  2524.92    1262309      0.0   

      splitFactor  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             1.0  
...           ...  
1253          1.0  
1254          1.0  
1255          1.0  
1256          1.0  
1257          1.0  

[1258 rows x 14 columns]

In [3]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from tensorflow import keras

In [4]:
data.head()

symbol                       date   close    high       low    open  \
0   GOOG  2016-06-14 00:00:00+00:00  718.27  722.47  713.1200  716.48   
1   GOOG  2016-06-15 00:00:00+00:00  718.92  722.98  717.3100  719.00   
2   GOOG  2016-06-16 00:00:00+00:00  710.36  716.65  703.2600  714.91   
3   GOOG  2016-06-17 00:00:00+00:00  691.72  708.82  688.4515  708.65   
4   GOOG  2016-06-20 00:00:00+00:00  693.71  702.48  693.4100  698.77   

    volume  adjClose  adjHigh    adjLow  adjOpen  adjVolume  divCash  \
0  1306065    718.27   722.47  713.1200   716.48    1306065      0.0   
1  1214517    718.92   722.98  717.3100   719.00    1214517      0.0   
2  1982471    710.36   716.65  703.2600   714.91    1982471      0.0   
3  3402357    691.72   708.82  688.4515   708.65    3402357      0.0   
4  2082538    693.71   702.48  693.4100   698.77    2082538      0.0   

   splitFactor  
0          1.0  
1          1.0  
2          1.0  
3          1.0  
4          1.0

In [5]:
data.tail()

symbol                       date    close      high        low     open  \
1253   GOOG  2021-06-07 00:00:00+00:00  2466.09  2468.000  2441.0725  2451.32   
1254   GOOG  2021-06-08 00:00:00+00:00  2482.85  2494.495  2468.2400  2479.90   
1255   GOOG  2021-06-09 00:00:00+00:00  2491.40  2505.000  2487.3300  2499.50   
1256   GOOG  2021-06-10 00:00:00+00:00  2521.60  2523.260  2494.0000  2494.01   
1257   GOOG  2021-06-11 00:00:00+00:00  2513.93  2526.990  2498.2900  2524.92   

       volume  adjClose   adjHigh     adjLow  adjOpen  adjVolume  divCash  \
1253  1192453   2466.09  2468.000  2441.0725  2451.32    1192453      0.0   
1254  1253253   2482.85  2494.495  2468.2400  2479.90    1253253      0.0   
1255  1006337   2491.40  2505.000  2487.3300  2499.50    1006337      0.0   
1256  1561733   2521.60  2523.260  2494.0000  2494.01    1561733      0.0   
1257  1262309   2513.93  2526.990  2498.2900  2524.92    1262309      0.0   

      splitFactor  
1253          1.0  
1254          1.0  
1255          1.0  
1256          1.0  
1257          1.0

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   symbol       1258 non-null   object 
 1   date         1258 non-null   object 
 2   close        1258 non-null   float64
 3   high         1258 non-null   float64
 4   low          1258 non-null   float64
 5   open         1258 non-null   float64
 6   volume       1258 non-null   int64  
 7   adjClose     1258 non-null   float64
 8   adjHigh      1258 non-null   float64
 9   adjLow       1258 non-null   float64
 10  adjOpen      1258 non-null   float64
 11  adjVolume    1258 non-null   int64  
 12  divCash      1258 non-null   float64
 13  splitFactor  1258 non-null   float64
dtypes: float64(10), int64(2), object(2)
memory usage: 137.7+ KB


In [7]:
data.drop_duplicates()

symbol                       date    close      high        low     open  \
0      GOOG  2016-06-14 00:00:00+00:00   718.27   722.470   713.1200   716.48   
1      GOOG  2016-06-15 00:00:00+00:00   718.92   722.980   717.3100   719.00   
2      GOOG  2016-06-16 00:00:00+00:00   710.36   716.650   703.2600   714.91   
3      GOOG  2016-06-17 00:00:00+00:00   691.72   708.820   688.4515   708.65   
4      GOOG  2016-06-20 00:00:00+00:00   693.71   702.480   693.4100   698.77   
...     ...                        ...      ...       ...        ...      ...   
1253   GOOG  2021-06-07 00:00:00+00:00  2466.09  2468.000  2441.0725  2451.32   
1254   GOOG  2021-06-08 00:00:00+00:00  2482.85  2494.495  2468.2400  2479.90   
1255   GOOG  2021-06-09 00:00:00+00:00  2491.40  2505.000  2487.3300  2499.50   
1256   GOOG  2021-06-10 00:00:00+00:00  2521.60  2523.260  2494.0000  2494.01   
1257   GOOG  2021-06-11 00:00:00+00:00  2513.93  2526.990  2498.2900  2524.92   

       volume  adjClose   adjHigh     adjLow  adjOpen  adjVolume  divCash  \
0     1306065    718.27   722.470   713.1200   716.48    1306065      0.0   
1     1214517    718.92   722.980   717.3100   719.00    1214517      0.0   
2     1982471    710.36   716.650   703.2600   714.91    1982471      0.0   
3     3402357    691.72   708.820   688.4515   708.65    3402357      0.0   
4     2082538    693.71   702.480   693.4100   698.77    2082538      0.0   
...       ...       ...       ...        ...      ...        ...      ...   
1253  1192453   2466.09  2468.000  2441.0725  2451.32    1192453      0.0   
1254  1253253   2482.85  2494.495  2468.2400  2479.90    1253253      0.0   
1255  1006337   2491.40  2505.000  2487.3300  2499.50    1006337      0.0   
1256  1561733   2521.60  2523.260  2494.0000  2494.01    1561733      0.0   
1257  1262309   2513.93  2526.990  2498.2900  2524.92    1262309      0.0   

      splitFactor  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             1.0  
...           ...  
1253          1.0  
1254          1.0  
1255          1.0  
1256          1.0  
1257          1.0  

[1258 rows x 14 columns]

In [8]:
data.isnull().sum()

symbol         0
date           0
close          0
high           0
low            0
open           0
volume         0
adjClose       0
adjHigh        0
adjLow         0
adjOpen        0
adjVolume      0
divCash        0
splitFactor    0
dtype: int64

In [9]:
data.corr()

C:\Users\sweth\AppData\Local\Temp\ipykernel_7568\2627137660.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()


close      high       low      open    volume  adjClose  \
close        1.000000  0.999528  0.999586  0.999083 -0.025574  1.000000   
high         0.999528  1.000000  0.999354  0.999575 -0.012470  0.999528   
low          0.999586  0.999354  1.000000  0.999499 -0.035184  0.999586   
open         0.999083  0.999575  0.999499  1.000000 -0.021381  0.999083   
volume      -0.025574 -0.012470 -0.035184 -0.021381  1.000000 -0.025574   
adjClose     1.000000  0.999528  0.999586  0.999083 -0.025574  1.000000   
adjHigh      0.999528  1.000000  0.999354  0.999575 -0.012470  0.999528   
adjLow       0.999586  0.999354  1.000000  0.999499 -0.035184  0.999586   
adjOpen      0.999083  0.999575  0.999499  1.000000 -0.021381  0.999083   
adjVolume   -0.025574 -0.012470 -0.035184 -0.021381  1.000000 -0.025574   
divCash           NaN       NaN       NaN       NaN       NaN       NaN   
splitFactor       NaN       NaN       NaN       NaN       NaN       NaN   

              adjHigh    adjLow   adjOpen  adjVolume  divCash  splitFactor  
close        0.999528  0.999586  0.999083  -0.025574      NaN          NaN  
high         1.000000  0.999354  0.999575  -0.012470      NaN          NaN  
low          0.999354  1.000000  0.999499  -0.035184      NaN          NaN  
open         0.999575  0.999499  1.000000  -0.021381      NaN          NaN  
volume      -0.012470 -0.035184 -0.021381   1.000000      NaN          NaN  
adjClose     0.999528  0.999586  0.999083  -0.025574      NaN          NaN  
adjHigh      1.000000  0.999354  0.999575  -0.012470      NaN          NaN  
adjLow       0.999354  1.000000  0.999499  -0.035184      NaN          NaN  
adjOpen      0.999575  0.999499  1.000000  -0.021381      NaN          NaN  
adjVolume   -0.012470 -0.035184 -0.021381   1.000000      NaN          NaN  
divCash           NaN       NaN       NaN        NaN      NaN          NaN  
splitFactor       NaN       NaN       NaN        NaN      NaN          NaN

In [28]:
data.divCash.sum()

0.0

In [11]:
data.columns

Index(['symbol', 'date', 'close', 'high', 'low', 'open', 'volume', 'adjClose',
       'adjHigh', 'adjLow', 'adjOpen', 'adjVolume', 'divCash', 'splitFactor'],
      dtype='object')

In [12]:
goog_stock = data.iloc[:,5:6].values
goog_stock

array([[ 716.48],
       [ 719.  ],
       [ 714.91],
       ...,
       [2499.5 ],
       [2494.01],
       [2524.92]])

In [13]:
min_scaled = MinMaxScaler(feature_range=(0,1))
data['open'] = min_scaled.fit_transform(goog_stock)
data['open']

0       0.024532
1       0.025891
2       0.023685
3       0.020308
4       0.014979
          ...   
1253    0.960300
1254    0.975716
1255    0.986289
1256    0.983327
1257    1.000000
Name: open, Length: 1258, dtype: float64

In [14]:
data.iloc[:,2:3].values

array([[ 718.27],
       [ 718.92],
       [ 710.36],
       ...,
       [2491.4 ],
       [2521.6 ],
       [2513.93]])

In [15]:
df1 = data.iloc[:,2:3].values
data['close'] = min_scaled.fit_transform(df1)
data['close']

0       0.026984
1       0.027334
2       0.022716
3       0.012658
4       0.013732
          ...   
1253    0.970049
1254    0.979092
1255    0.983705
1256    1.000000
1257    0.995862
Name: close, Length: 1258, dtype: float64

In [16]:
X = data.drop(['date','symbol','close'],axis =1)
y = data['close']

In [17]:
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size=  0.3)

In [18]:
X_train = np.expand_dims(X_train, axis=-1)
X_train = np.reshape(X_train, (X_train.shape[0],X_train.shape[1],1))
X_train= np.array(X_train)
print(X_train.shape,y_train.shape, X_test.shape, y_test.shape)

(880, 11, 1) (880,) (378, 11) (378,)


In [19]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
#int(X_train[1]).dtyp

In [20]:
X_test = np.expand_dims(X_test, axis=-1)
X_test = np.reshape(X_test, (X_test.shape[0],X_test.shape[1],1))
X_test= np.array(X_test)

In [21]:
model = keras.Sequential([
    keras.layers.LSTM(units=50, return_sequences=True,
                      input_shape=(X_train.shape[1], 1)
                     ),
    keras.layers.Dropout(0.2),
    keras.layers.LSTM(units=50, return_sequences=True),
    keras.layers.Dropout(0.2),
    keras.layers.LSTM(units=50),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(units=1)
])

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mean_absolute_error'])

In [22]:
model.fit(X_train,y_train,epochs = 10)

Epoch 1/10
28/28 [==============================] - 9s 19ms/step - loss: 0.0529 - mean_absolute_error: 0.1756
Epoch 2/10
28/28 [==============================] - 0s 16ms/step - loss: 0.0462 - mean_absolute_error: 0.1593
Epoch 3/10
28/28 [==============================] - 1s 22ms/step - loss: 0.0420 - mean_absolute_error: 0.1526
Epoch 4/10
28/28 [==============================] - 0s 13ms/step - loss: 0.0361 - mean_absolute_error: 0.1386
Epoch 5/10
28/28 [==============================] - 0s 15ms/step - loss: 0.0199 - mean_absolute_error: 0.1110
Epoch 6/10
28/28 [==============================] - 0s 14ms/step - loss: 0.0088 - mean_absolute_error: 0.0736
Epoch 7/10
28/28 [==============================] - 0s 15ms/step - loss: 0.0048 - mean_absolute_error: 0.0530
Epoch 8/10
28/28 [==============================] - 0s 14ms/step - loss: 0.0036 - mean_absolute_error: 0.0445
Epoch 9/10
28/28 [==============================] - 0s 14ms/step - loss: 0.0026 - mean_absolute_error: 0.0387
Epoch 10/1

In [23]:
predicted = model.predict(X_test)
predicted[:2]

12/12 [==============================] - 2s 9ms/step


array([[0.49910602],
       [0.3128755 ]], dtype=float32)

In [24]:
y_test[:2]

C:\Users\sweth\AppData\Local\Temp\ipykernel_7568\1739259011.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  y_test[:2]


1033    0.485734
547     0.294668
Name: close, dtype: float64